### PR TITLE
Package as OT module

### PR DESCRIPTION
**Pull request by tupui**
This proposes the following:

- Packaging with a `setup.py`,
- *Sphinx* documentation following OT modules's template,
- Replace `unittest` by `pytest` and setup CI,
- Replace `pylab` by `matplotlib`.

### CODE REVIEW

**Comment by tupui** [comment]
My next steps:

- [ ] Migrate the examples,
- [ ] Complet the documentation,
- [ ] Write code documentation,
- [ ] Code refactoring.

**Comment by tupui** [comment]
@mbaudin47 Can we relax the constrain on the input sample? I find the use of a `ProcessSample` quite complicated for just a 3D matrix.

In the current code, we are constructing a mesh to create this object and we pass it to  `ProcessHighDensityRegionAlgorithm`. As soon as the class is instantiated, we undo this to go back to the `sample`.

Also, the mesh is not really used so we would just pass it as an extra argument.

**Comment by mbaudin47** [comment]
Please look at the roadmap I just completed in the main README. 

On the specific ProcessSample point, I do think this is the correct object to manipulate for the ProcessHighDensityRegionAlgorithm class. The mesh *is* used in the plot (but not in the PCA). However, the mesh is to be used in the Karhunen-Loeve dimension reduction, which is an option we should implement.

**Comment by mbaudin47** [comment]
By the way, thank you very much for the work: it already seems excellent to me, even if all the work is not finished yet.

**Pull request merged**
